// Generated by CoffeeScript 1.8.0
(function() {
  var CommonsCtrl, ProductCtrl;

  ProductCtrl = require("./../ctrl/productCtrl");

  CommonsCtrl = require("./../ctrl/commonsCtrl");

  CommonsCtrl.cruiseArea(function(err, res) {
    return console.log(err, JSON.stringify(res));
  });

  CommonsCtrl.travelLocation(function(err, res) {
    return console.log(err, JSON.stringify(res));
  });

  CommonsCtrl.ship(function(err, res) {
    return console.log(err, JSON.stringify(res));
  });

}).call(this);
