// Generated by CoffeeScript 1.8.0
(function() {
  var ProductCtrl, async;

  ProductCtrl = require("./../ctrl/productCtrl");

  async = require("async");

  exports.index = function(req, res) {
    return ProductCtrl.productList(null, null, null, "2015-07", null, true, function(err, results) {
      console.log(results);
      return res.render("index", {
        products: results.productList
      });
    });
  };

  exports.search = function(req, res) {
    return res.render("search");
  };

  exports.detail = function(req, res) {
    var pid;
    pid = req.params.pid;
    return async.series([
      function(cb) {
        return ProductCtrl.productDetail(pid, function(err, result) {
          return cb(err, result);
        });
      }, function(cb) {
        return ProductCtrl.productFee(pid, function(err, result) {
          return cb(err, result);
        });
      }
    ], function(err, results) {
      var r;
      r = results[0];
      r.fees = results[1].fees;
      console.log(r);
      return res.render("prodInfo", r);
    });
  };

}).call(this);
