// Generated by CoffeeScript 1.8.0
(function() {
  var MemberCtrl, ProductCtrl, async;

  ProductCtrl = require("./../ctrl/productCtrl");

  MemberCtrl = require("./../ctrl/memberCtrl");

  async = require("async");

  exports.doLogin = function(req, res) {
    var loginName, password;
    loginName = req.body.loginName;
    password = req.body.password;
    return MemberCtrl.login(loginName, password, function(err, result) {
      if (err == null) {
        req.session.user = result;
      }
      return res.redirect("/");
    });
  };

  exports.checkLogin = function(req, res, next) {
    if (req.session.user != null) {
      return next();
    } else {
      return res.render("login");
    }
  };

  exports.index = function(req, res) {
    return ProductCtrl.productList(null, null, null, "2015-07", null, true, function(err, results) {
      return res.render("index", {
        products: results.productList
      });
    });
  };

  exports.search = function(req, res) {
    return res.render("search");
  };

  exports.detail = function(req, res) {
    var pid;
    pid = req.params.pid;
    return async.series([
      function(cb) {
        return ProductCtrl.productDetail(pid, function(err, result) {
          return cb(err, result);
        });
      }, function(cb) {
        return ProductCtrl.productFee(pid, function(err, result) {
          return cb(err, result);
        });
      }
    ], function(err, results) {
      var r;
      r = results[0];
      r.fees = results[1].fees;
      return res.render("prodInfo", r);
    });
  };

}).call(this);
