// Generated by CoffeeScript 1.8.0
(function() {
  var WeixinCtrl;

  WeixinCtrl = require("./../ctrl/weixinCtrl");

  exports.check = function(req, res) {
    var echostr, nonce, signature, timestamp;
    signature = req.query.signature;
    timestamp = req.query.timestamp;
    nonce = req.query.nonce;
    echostr = req.query.echostr;
    if (WeixinCtrl.check(timestamp, nonce, signature)) {
      return res.send(echostr);
    } else {
      return res.end();
    }
  };

  exports.msg = function(req, res) {
    var nonce, signature, timestamp;
    signature = req.query.signature;
    timestamp = req.query.timestamp;
    nonce = req.query.nonce;
    return res.send("");
  };

}).call(this);
