// Generated by CoffeeScript 1.8.0
(function() {
  var MemberCtrl, config, fs, https;

  https = require("https");

  fs = require("fs");

  config = require("./../config/config.json");

  MemberCtrl = (function() {
    function MemberCtrl() {}

    MemberCtrl.login = function(loginName, password, fn) {
      var options, req;
      options = {
        hostname: "www.huiyoulun.com",
        port: 443,
        path: "/services/authuser?loginName=" + loginName + "&password=" + password,
        method: 'GET',
        rejectUnauthorized: true
      };
      req = https.request(options, function(res) {
        var _data;
        res.setEncoding("utf8");
        _data = "";
        res.on("data", function(chunk) {
          return _data += chunk;
        });
        return res.on("end", function() {
          var result;
          console.log(_data);
          result = JSON.parse(_data);
          return fn(null, result);
        });
      });
      req.end();
      return req.on("error", function(e) {
        console.log(e);
        return fn(e);
      });
    };

    return MemberCtrl;

  })();

  module.exports = MemberCtrl;

}).call(this);
