// Generated by CoffeeScript 1.8.0
(function() {
  var WeixinCtrl, config, crypto, request;

  config = require("./../config/weixin.json");

  request = require("request");

  crypto = require("crypto");

  WeixinCtrl = (function() {
    function WeixinCtrl() {}

    WeixinCtrl.check = function(timestamp, nonce, signature) {
      var currSign, tmp;
      tmp = [config.token, timestamp, nonce].sort().join('');
      currSign = crypto.createHash("sha1").update(tmp).digest("hex");
      return currSign === signature;
    };

    WeixinCtrl.accessToken = function(fn) {
      var url;
      url = "https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=" + config.appID + "&secret=" + config.appSecret;
      return request({
        url: url,
        timeout: 3000
      }, function(err, response, body) {
        var res;
        if (err) {
          return fn(err);
        } else {
          res = body != null ? JSON.parse(body) : {};
          if (res.error != null) {
            return fn(new Error(res.error));
          } else {
            return fn(null, res);
          }
        }
      });
    };

    WeixinCtrl.codeAccessToken = function(code, fn) {
      var url;
      url = "https://api.weixin.qq.com/sns/oauth2/access_token?grant_type=authorization_code&appid=" + config.appID + "&secret=" + config.appSecret + "&code=" + code;
      return request({
        url: url,
        timeout: 3000
      }, function(err, response, body) {
        var res;
        if (err) {
          return fn(err);
        } else {
          res = body != null ? JSON.parse(body) : {};
          if (res.error != null) {
            return fn(new Error(res.error));
          } else {
            return fn(null, res);
          }
        }
      });
    };

    return WeixinCtrl;

  })();

  module.exports = WeixinCtrl;

}).call(this);
