// Generated by CoffeeScript 1.8.0
(function() {
  var WeixinCtrl, config, crypto;

  config = require("./../config/weixin.json");

  crypto = require("crypto");

  WeixinCtrl = (function() {
    function WeixinCtrl() {}

    WeixinCtrl.check = function(timestamp, nonce, signature) {
      var currSign, tmp;
      tmp = [config.token, timestamp, nonce].sort().join('');
      currSign = crypto.createHash("sha1").update(tmp).digest("hex");
      return currSign === signature;
    };

    return WeixinCtrl;

  })();

  module.exports = WeixinCtrl;

}).call(this);
